# Uncommented options are not recommended for modification
# æœªæ ‡æ³¨é‡Šçš„é€‰é¡¹å»ºè®®ä¸è¦ä¿®æ”¹

baseURL = 'https://hugo-blog-navy.vercel.app/'
languageCode = 'en-us'

# website title
# ç½‘ç«™æ ‡é¢˜
title = 'conghuynhğŸ‘»'
# theme
# ä¸»é¢˜
theme = "NewBee"
# Good Theme:
# https://github.com/CaiJimmy/hugo-theme-stack-starter
# https://github.com/xioyito/NewBee
# default content of website
# ç½‘ç«™é»˜è®¤è¯­è¨€
defaultContentLanguage = "en"
# whether to use robots.txt
# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT = true
# whether to use git info
# æ˜¯å¦ä½¿ç”¨ git info
enableGitInfo = false
# length of summary
# æ‘˜è¦çš„å­—æ•°é™åˆ¶
summaryLength = 50

# If true, auto-detect Chinese/Japanese/Korean Languages in the content.
# This will make .Summary and .WordCount behave correctly for CJK languages.
# ä¸­æ—¥éŸ©è¯­è¨€è¯·æ”¹ä¸º true
hasCJKLanguage = true

[author]
    name = "conghuynho"
    description = "The only thing we have to fear is fear itself."
    # profile photo of author in author card
    # ä½œè€…å¤´åƒ
    image = "/images/author.jpeg"
    # link of followme in author card and footer
    # ä½œè€…å¡ç‰‡é‡Œ followme å’Œé¡µè„šä½œè€…çš„é“¾æ¥
    link = "https://github.com/conghuynhho"

# Taxonomies
[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[params]
    [params.site]
        onlyOneLang = true
        # style of theme: auto, light, dark
        mode = 'auto'
    # page configuration
    # é¡µé¢é…ç½®
    [params.page]

        # top image in home page, note that the "/" in path is necessary, the same applies below
        # ä¸»é¡µçš„é¡¶éƒ¨å›¾ï¼Œè·¯å¾„å¼€å¤´â€/â€œæ˜¯å¿…éœ€çš„ã€‚ä¸‹åŒ
        homeTopImg = "/images/home.jpg"
        # title in home top image, support Markdown
        # ä¸»é¡µæ ‡é¢˜ï¼Œæ”¯æŒMarkdownè¯­æ³•
        homeTitle = "Huynh"
        # font size(px)
        # ä¸»é¡µæ ‡é¢˜å­—å·ï¼ˆå•ä½ï¼špxï¼‰
        homeTitleFontSize = 40
        # content in home top image, support Markdown
        # ä¸»é¡µå†…å®¹ï¼Œæ”¯æŒMarkdownè¯­æ³•
        homeContent = "Life is really simple, but we insist on making it complicated."
        # font size(px)
        # ä¸»é¡µå†…å®¹å­—å·ï¼ˆå•ä½ï¼špxï¼‰
        homeContentFontSize = 20

        # top image in categories terms page
        # åˆ†ç±»é¡µé¢çš„é¡¶éƒ¨å›¾
        categoryTopImg = "/images/categories.jpg"
        # description of categories terms page
        # å­æ ‡é¢˜
        categoryDes = "description of categories page"

        # top image in series terms page
        # ç³»åˆ—é¡µé¢çš„é¡¶éƒ¨å›¾
        seriesTopImg = "/images/series.jpg"
        # description of series terms page
        # å­æ ‡é¢˜
        seriesDes = "description of series page"

        # top image in tags terms page
        # æ ‡ç­¾é¡µé¢çš„é¡¶éƒ¨å›¾
        tagTopImg = "/images/tag.jpg"
        # description of tags terms page
        # å­æ ‡é¢˜
        tagDes = "description of tags page"

        # top image in allposts page
        # æ‰€æœ‰æ–‡ç« é¡µé¢çš„é¡¶éƒ¨å›¾
        allPostsTopImg = "/images/allPosts.jpg"
        # description of allposts page
        # å­æ ‡é¢˜
        allPostsDes = "description of allposts page"

        # top image in about page
        # å…³äºé¡µé¢çš„é¡¶éƒ¨å›¾
        aboutTopImg = "/images/about.jpg"
        # description of about page
        # å­æ ‡é¢˜
        aboutDes = "description of about page"

        # default image for a post without "image" param
        # å½“æ–‡ç« æ²¡æœ‰è®¾ç½®å›¾ç‰‡æ—¶ï¼Œå°†ç”¨æ­¤å›¾æ¥æ›¿ä»£
        postsTopImg = "/images/default.jpg"

        # ä¸»é¡µæ–‡ç« æœ€å¤§æ˜¾ç¤ºæ•°é‡
        maxHomePostCount = 5
        # ç›¸å…³æ–‡ç« æœ€å¤§æ˜¾ç¤ºæ•°é‡
        maxPageRelatedCount = 5
        # æœ€æ–°æ–‡ç« æœ€å¤§æ˜¾ç¤ºæ•°é‡
        maxPageNewestCount = 5

    # Valine comment
    # Valineè¯„è®ºï¼ˆè¯¦æƒ…è¯·ç§»æ­¥ï¼šhttps://valine.js.org/ï¼‰
    [params.valine]
        # æ˜¯å¦å¼€å¯Valineè¯„è®ºç³»ç»Ÿ
        enable = false
        # appidï¼Œå…·ä½“è¯·å‚è€ƒï¼šhttps://valine.js.org/configuration.html#appId
        appid = 'xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxx'
        # appKeyï¼Œå…·ä½“è¯·å‚è€ƒï¼šhttps://valine.js.org/configuration.html#appKey
        appkey = 'xxxxxxxxxxxxxxxxxxxxxxxx'
        # è¾“å…¥æ¡†æç¤ºæ–‡å­—
        placeholder = 'è¾“å…¥ä½ çš„è¯„è®º'
        # å¤´åƒï¼Œå…·ä½“è¯·å‚è€ƒï¼šhttps://valine.js.org/avatar.html
        avatar = 'robohash'
        # è¯„è®ºæ—¶è¦æ±‚çš„å¿…é¡»å¡«å†™é¡¹ï¼Œå¯é€‰å€¼ï¼š['nick']æˆ–['nick','mail']
        requiredFields = ['nick']
        # æ–‡ç« è®¿é—®é‡ç»Ÿè®¡
        visitor = true
        # å•é¡µæœ€å¤§è¯„è®ºæ•°ç›®
        pageSize = 5

    # footer
    # é¡µé¢åº•éƒ¨é…ç½®
    [params.footer]
        # whether to enable footer
        enable = true
        # copyright
        copyRight = false
        from = 2022
        # wheher to enable count of visitor and view
        visitor = true
        # wheher to enable theme information
        themeInfo = false

    # aplayer, se  more: https://aplayer.js.org/#/zh-Hans/
    # éŸ³ä¹æ’­æ”¾å™¨é…ç½®ï¼Œè¯¦æƒ…è¯·ç§»æ­¥ï¼šhttps://aplayer.js.org/#/zh-Hans/
    [params.aplayer]
        enable = true
        server = "netease"
        type = "playlist"
        id = 752439587
        fixed = true
        autoplay = false
        loop = "all"
        order = "random"
        preload = "auto"
        list_folded = "true"
        list_max_height = "500px"
        lrc_type = 1

# related configuration, see more: https://gohugo.io/content-management/related/
# ç›¸å…³æ–‡ç« çš„é…ç½®ã€‚è¯¦æƒ…è¯·ç§»æ­¥ï¼šhttps://gohugo.io/content-management/related/
[related]
    # å–å€¼0-100ä¹‹é—´ï¼Œè¶Šå°åŒ¹é…åˆ°çš„æ–‡ç« è¶Šå¤šï¼Œä½†å‡†ç¡®æ€§ç¨å·®
    threshold = 0
    # å…è®¸åŒ…å«æœ€æ–°çš„æ–‡ç« 
    includeNewer = true
    # è®¾ç½®ä¸ºtrueæ—¶ï¼Œå¯ä»¥åœ¨ç´¢å¼•å’ŒæŸ¥è¯¢ä¸­åŒæ—¶ä½¿ç”¨å°å†™å…³é”®å­—ã€‚
    # è¿™å¯èƒ½ä¼šåœ¨è½»å¾®çš„æ€§èƒ½æŸå¤±ä¸‹æä¾›æ›´å‡†ç¡®çš„ç»“æœã€‚
    # ä¹Ÿå¯ä»¥åœ¨ä¸‹é¢çš„å­é¡¹ä¸­åˆ†åˆ«è®¾ç½®æ­¤å€¼ã€‚
    toLower = false

    [[related.indices]]
        # åŒ¹é…ç±»åˆ«
        name = "categories"
        # ä¸€ä¸ªæ•´æ•°æƒé‡ï¼Œè¡¨ç¤ºæ­¤å‚æ•°ç›¸å¯¹äºå…¶ä»–å‚æ•°çš„é‡è¦æ€§ã€‚
        # å¯ä»¥æ˜¯0ï¼Œæœ‰å…³é—­è¿™ä¸ªç´¢å¼•çš„æ•ˆæœï¼Œç”šè‡³æ˜¯è´Ÿæ•°ã€‚
        # ä½¿ç”¨ä¸åŒçš„å€¼è¿›è¡Œæµ‹è¯•ï¼Œä»¥æŸ¥çœ‹æœ€é€‚åˆæ‚¨çš„å†…å®¹çš„å€¼ã€‚
        weight = 100
        # åŒä¸ŠtoLower
        toLower = false

    [[related.indices]]
        name = "tags"
        weight = 80
        toLower = false

    [[related.indices]]
        name = "date"
        weight = 10

# Markup related configuration in Hugo
# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
    # syntax highlight, see more: https://gohugo.io/functions/highlight/
    # è¯­æ³•é«˜äº®ï¼Œè¯¦æƒ…è¯·ç§»æ­¥ï¼šhttps://gohugo.io/functions/highlight/
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        # æ˜¾ç¤ºæ¯ä¸€è¡Œä»£ç å‰çš„åºå·
        lineNos = true
        anchorLineNos = false
        lineNumbersInTable = true
        noClasses = false
        noHl = false
        # ä»£ç é«˜äº®æ ·å¼ï¼Œæ›´å¤šæ ·å¼è¯·ç§»æ­¥ï¼šhttps://xyproto.github.io/splash/docs/
        style = 'monokailight'
        tabWidth = 4

    # enable the following code if there are html statements in your md file
    # å¦‚æœmdæ–‡ä»¶ä¸­æœ‰htmlè¯­å¥ï¼Œè¯·å¯ç”¨ä»¥ä¸‹ä»£ç 
    # [markup.goldmark]
    #     [markup.goldmark.renderer]
    #         unsafe = true

# å¤šè¯­è¨€è®¾ç½®
[languages]
    [languages.en]
        languageName = 'English'
        weight = 1
        contentDir = 'content/english'
        disable = false
        [languages.en.menus]
        # navigation entries
        # å¯¼èˆªæ å­é¡¹
        [[languages.en.menus.main]]
            # åç§°
            name = "Home"
            # è·¯å¾„
            url = "/"
            # order weight, more small more close to left, at least 1
            # æ’åºçš„æƒé‡ï¼Œè¶Šå°è¶Šé å‰ï¼ˆå·¦ï¼‰ï¼Œæœ€å°ä¸º1
            weight = 1
            # icon from FontAwesome in front of single entry
            # å›¾æ ‡ï¼Œæœ¬ä¸»é¢˜ä½¿ç”¨çš„å›¾æ ‡æ¥è‡ªFontAwesome
            pre = "<i class='fa fa-home'></i>"
        [[languages.en.menus.main]]
            name = "Posts"
            url = "/posts"
            weight = 2
            pre = "<i class='fa fa-book'></i>"
        [[languages.en.menus.main]]
            name = "Categories"
            url = "/categories"
            weight = 3
            pre = "<i class='fa fa-folder-open'></i>"
        [[languages.en.menus.main]]
            name = "Series"
            url = "/series"
            weight = 4
            pre = "<i class='fa fa-gears'></i>"
        [[languages.en.menus.main]]
            name = "Tags"
            url = "/tags"
            weight = 5
            pre = "<i class='fa fa-tags'></i>"
        [[languages.en.menus.main]]
            name = "About"
            url = "/about"
            weight = 6
            pre = "<i class='fa fa-info-circle'></i>"

        # social, maxum 6
        # ä½œè€…å¡ç‰‡ç¤¾äº¤é“¾æ¥ï¼Œæœ€å¤š6ä¸ª
        [[languages.en.menus.social]]
            name = "GitHub"
            url = "https://github.com/xioyito"
            pre = "<i class='fa fa-github'></i>"
            weight = 1
        [[languages.en.menus.social]]
            name = "YouTube"
            url = "https://www.youtube.com"
            pre = "<i class='fa fa-youtube'></i>"
            weight = 2

        # sponsor, maxum 3
        # èµèµï¼Œæœ€å¤šæ”¯æŒ3ä¸ª
        [[languages.en.menus.sponsor]]
            name = "Wechat"
            url = "/images/sponsor/Wechat.jpeg"
            weight = 1
        [[languages.en.menus.sponsor]]
            name = "Alipay"
            url = "/images/sponsor/Alipay.jpeg"
            weight = 2

    [languages.zh]
        disable = false
        languageName = 'ç®€ä½“ä¸­æ–‡'
        weight = 2
        contentDir = 'content/chinese'
        [languages.zh.menus]
            [[languages.zh.menus.main]]
                name = "ä¸»é¡µ"
                url = "/zh"
                weight = 1
                pre = "<i class='fa fa-home'></i>"
            [[languages.zh.menus.main]]
                name = "æ–‡ç« "
                url = "/zh/posts"
                weight = 2
                pre = "<i class='fa fa-book'></i>"
            [[languages.zh.menus.main]]
                name = "åˆ†ç±»"
                url = "/zh/categories"
                weight = 3
                pre = "<i class='fa fa-folder-open'></i>"
            [[languages.zh.menus.main]]
                name = "ç³»åˆ—"
                url = "/zh/series"
                weight = 4
                pre = "<i class='fa fa-gears'></i>"
            [[languages.zh.menus.main]]
                name = "æ ‡ç­¾"
                url = "/zh/tags"
                weight = 5
                pre = "<i class='fa fa-tags'></i>"
            [[languages.zh.menus.main]]
                name = "å…³äº"
                url = "/zh/about"
                weight = 6
                pre = "<i class='fa fa-info-circle'></i>"
            [[languages.zh.menus.social]]
                name = "GitHub"
                url = "https://github.com/xioyito"
                pre = "<i class='fa fa-github'></i>"
                weight = 1
            [[languages.zh.menus.social]]
                name = "YouTube"
                url = "https://www.youtube.com"
                pre = "<i class='fa fa-youtube'></i>"
                weight = 2
            [[languages.zh.menus.sponsor]]
                name = "å¾®ä¿¡"
                url = "/images/sponsor/Wechat.jpeg"
            [[languages.zh.menus.sponsor]]
                name = "æ”¯ä»˜å®"
                url = "/images/sponsor/Alipay.jpeg"

